### ISSUE TITLE
[1.16.4] Bees won't go in new hives if they're carrying pollen

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#110]
Disclaimer: I'm not certain this is not intended behaviour ^^'

**Describe the bug**
If you change a beehive (to a different tier or type) while a bee that currently lives their still has pollen, then the bee won't accept the new hive. They have to go back to the same type/tier hive and make a honeycomb before they can accept the new hives as their new home. In short: the bee needs to have no pollen to accept a new type of beehive.

Edit: Just found out that the bees need to have no accessible flowers too when they come out of their current hives before you put them in a jar and do the hive swap

**To Reproduce**
(I hope you can extract reproduction steps from the description)

**Expected behavior**
For the bee to accept it's new home.

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version 1.16.4-35.1.29
 - ResourcefulBees1.16.3-1.16.4-0.5.7b

**Additional context**
Original issue/reporter: https://github.com/NillerMedDild/Enigmatica6/issues/763

**Comment by ThatGravyBoat** [comment]
I just tested this and couldn't reproduce it in my dev environment.
Ill explain what I did just because I didnt fully understand what you described.
1. I put down a normal t1 hive
2. let a bee go inside
3. let it get pollen again
4. replaced it with a t3
and the bee went back in without a hitch.
If I didnt do what you said just tell me and ill check again.

**Comment by protoelectric** [comment]
I'm having the same issue with an apiary. They just fly around in the apiary after collecting pollen.

**Comment by NielsPilgaard** [comment]
> I put down a normal t1 hive
let a bee go inside
let it get pollen again
replaced it with a t3

That is also how I understood it - @stupex could you please confirm whether that is how to reproduce the bug with new hives?

**Comment by stupex** [comment]
I wasn't exactly sure what the problem was initially. After much testing I figured out what the bug was:

Bees won't accept any other hive besides tier 1s initially.

So if you spawned a bee (by jar/egg) and you only have tier 2+ hives in place, it will never enter it because it will try to find a tier 1 hive (this is the bug). As soon as a tier 1 hive is placed, the bee will choose it as its home rather than the available higher tier hives.

**Video**: https://streamable.com/126qgt

**A work around I found:**
1. Let a bee get pollen and provide it with a tier 1 hive.
2. Remove all accessible flowers before the bee comes out of the tier 1 hive.
3. Place the bee in a jar after it comes out of the hive so that it won't go aggro when doing the hive swap.
4. Swap the tier 1 hive with another hive and place back some flowers.
5. Spawn the bee back. It will now accept any hive besides tier 1s.

**Video**: https://streamable.com/11td93

**Expected behavior**
For the bee to accept any hive.

**Comment by Epic428** [comment]
**All** Bees use the same backend code and **All** Tiered hives use the same backend code. I also cannot reproduce this bug. There's no logic that forces a bee to **only** select a T1 hive before any other hive.

**Comment by Epic428** [comment]
fixed in d0e4f1d39dff5b113cae2c2b1add2d8157d65706

**Comment by F0x06** [comment]
Mod version: 1.16.4-0.5.8b

Apparently i got the same issue, is anyone using a modpack like ATM-6 ? I reproduced the issue in ATM, but bees works fine with just JEI + ResourcefulBees installed.

How to reproduce:
1. Place some flowers
2. Place any Beehive greather than Tier 1
3. Spawn some Bees

The bees will fly around when full and never go inside the Beehive 

I'll create a separate issue in ATM-6 repo.

EDIT: Apparently after some time like 5-10m bees entered the beehive all all is working fine now.
