### ISSUE TITLE
Apiary only produces once, on bee unlock

### ISSUE THREAD

**Issue by akutamatata** [Team-Resourceful/ResourcefulBees#121]
**Describe the bug**
Apiary only produces resources when Unlocking bee, and then it won't produce any after. Also cannot set up to export bee out of the apiary without entering it(Not sure if that is intended or not)

I'm using ATM6, updated the mod to 0.58b though after it wasn't producing anything.

**To Reproduce**
1. Setup apiary
2. place "flowers" in apiary for the bees used
3. Place bee in import slot, and press import
4. wait for the ticks required, press unlock on bee so it gets released into the Apiary
5. 50/50 chance of it producing a set of resources(in this case 8 combs)

**Expected behavior**
Bee to be placed in apiary and every x minutes or something produce 8 combs.

In case I was doing it incorrectly, I also left bees in a Locked state for 10,000 ticks(~4 minutes) and received nothing

**please complete the following information:**
 - Forge Version 1.16.4 - 35.1.29
 - mod version: 0.58b

**Comment by Vaerys-Dawn** [comment]
Not a bug, you need to let your bees out to roam for them to pollenate off flowers and produce combs, locking them is to prevent them from leaving the hive allowing you to breed them or pull them out of the hive via a jar

**Comment by akutamatata** [comment]
I've left them inside pollinating for half an hour and they still have yet to produce anything.
They're flying around in their entity form

the ONLY TIME they produced something, is immediately after I unlocked them into it, after that they stopped, even while unlocked.

**Comment by Epic428** [comment]
the basics of how bees work is they pollinate a flower and collect nectar. the nectar drips from them and they look for a hive and store its position. they enter the hive wait a bit then leave and repeat the process. if they are stuck on finding a flower they won't have nectar. if they are stuck on finding a hive then it's likely bc the mod is not on 0.5.8b.

As for apiaries bees are only supposed to be locked in an apiary when you DON"T want them to produce combs or if you want to export them into a jar otherwise you must leave them unlocked and let them follow the basic process.

**Comment by akutamatata** [comment]
I am on 0.5.8b I updated last night when I realized there was a bug with only T1 working.

I have them unlocked, I unlocked them and left my computer running for half an hour while they were in bee/mob form inside the apiary, flying around.

**Comment by akutamatata** [comment]
> the basics of how bees work is they pollinate a flower and collect nectar. the nectar drips from them and they look for a hive and store its position. they enter the hive wait a bit then leave and repeat the process. if they are stuck on finding a flower they won't have nectar. if they are stuck on finding a hive then it's likely bc the mod is not on 0.5.8b.
> 
> As for apiaries bees are only supposed to be locked in an apiary when you DON"T want them to produce combs or if you want to export them into a jar otherwise you must leave them unlocked and let them follow the basic process.

I am on 0.5.8b I updated last night when I realized there was a bug with only T1 working.

I have them unlocked, I unlocked them and left my computer running for half an hour while they were in bee/mob form inside the apiary, flying around.

**Comment by Epic428** [comment]
do you have the correct flower for the bee? what does jei say the flower should be? generally the max time in hive for a bee is 2 minutes minus the hive time modification. so a bee will only stay in for that long and then leave to go to its flower and pollinate. if it's just flying around and not doing anything then it's likely because the flower being used isn't correct for the bee.

**Comment by akutamatata** [comment]
> do you have the correct flower for the bee? what does jei say the flower should be? generally the max time in hive for a bee is 2 minutes minus the hive time modification. so a bee will only stay in for that long and then leave to go to its flower and pollinate. if it's just flying around and not doing anything then it's likely because the flower being used isn't correct for the bee.

Yup I'll just boot up the map and take a screenshot.

I have multiple kinds in there, all with their correct flower. Like I said **It generated right when I pressed unlock,** and then it stopped after.

**Comment by Epic428** [comment]
post your latest.log also if you are on a server make sure the client and server match.

**Comment by akutamatata** [comment]
![2021-01-15_17 35 28](https://user-images.githubusercontent.com/37421153/104781029-1bcb9f00-5758-11eb-8752-ab9e6f31f76e.png)
![2021-01-15_17 34 06](https://user-images.githubusercontent.com/37421153/104781030-1c643580-5758-11eb-8e5d-29099bacc274.png)

Nope I'm on Single player

**Comment by Epic428** [comment]
logs?

**Comment by akutamatata** [comment]
[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/5823050/latest.log)

**Comment by Epic428** [comment]
there's no errors. try jarring the bee and placing it back down. verify with certainty you're on 0.5.8b or see if you can update to the 1.4.0b version of the pack that came out today. but otherwise your bee should be pollinating the flower assuming the diamond block is the correct flower for the bee.

**Comment by akutamatata** [comment]
After replacing the apiary and importing the bees, everything is working fine.
