### ISSUE TITLE
Bees despawning

### ISSUE THREAD

**Issue by B3tah3** [Team-Resourceful/ResourcefulBees#172]
**Describe the bug**
In the Sky Bees Modpack, any Resourceful Bees, but not Vanilla Bees, despawn after around 10 minutes. Obeserved with bred, summoned and spawnEgged Bees.

**To Reproduce**
1. Build a cube enclosure out of glass (5x5 interior).
2.  spawn in some bees
3. go into spectator, record screen and go afk.
4. the footage shows the bees disappear without taking damage

**Expected behavior**
Bees without hives should not despawn, just like vanilla bees.

**Screenshots or Crash Logs**
![despawn-before](https://user-images.githubusercontent.com/33493099/109493496-e02d3000-7a8c-11eb-91ff-9054d18499cf.png)

![despawn-after](https://user-images.githubusercontent.com/33493099/109493214-701eaa00-7a8c-11eb-91a0-3ce661fa2e7d.png)

**please complete the following information:**
 - Forge Version 35.1.38
 - Mod Version ResourcefulBees1.16.3-1.16.4-0.5.8b.jar

**Comment by Epic428** [comment]
This is not a bug. It is by design. Vanilla bees don’t spawn the same way as other passive mobs do since they only spawn as a result of being preloaded in the nests generated on trees.

Our bees however can spawn in world like passive mobs. As such we need to be able to manage that. So when our bees are not within 10 blocks of a hive or in range of a beecon or name tagged then they will despawn after ten consecutive minutes.

**Comment by Epic428** [comment]
Also because vanilla bees only come preloaded in generated nests this means there is a finite number of bees that will ever exist excluding breeding. Whereas there is an infinite number of our bees Bc they will always spawn given the criteria to do so has been met.

**Comment by B3tah3** [comment]
Ah thanks, so i can place a beehive outside the box to keeps the bees alive to keep breeding?

**Comment by ThatGravyBoat** [comment]
yes or you can leash them to a fence or name tag them or place the flower(s) they like in the box or put a beecon in range
