### ISSUE TITLE
Bees In Apiary

### ISSUE THREAD

**Issue by Nick633** [Team-Resourceful/ResourcefulBees#205]
Put bees on apiary and most or all of them collect on one corner of the multiblock, always the same corner, the back left corner. I try it on different world. Modpack: Delivery inc.
![2021-04-03_19 26 55](https://user-images.githubusercontent.com/81885647/113494095-591c0f00-94b3-11eb-9ee9-db07ec1bd6d0.png)
![2021-04-03_19 26 47](https://user-images.githubusercontent.com/81885647/113494097-5e795980-94b3-11eb-9488-4e411d05e3fc.png)
![2021-04-03_19 26 37](https://user-images.githubusercontent.com/81885647/113494100-620ce080-94b3-11eb-8802-02980ef9a54a.png)

**Comment by Nick633** [comment]
3 different Apiaries.

**Comment by sztosz** [comment]
I can confirm that. Same modpack, same behaviour. In my case they tend to stick to the southeast corner, it's roughly the same direction where I have gathered them from, but I doubt that's the root of the problem. Moving them between apiaries, and just observing, I believe it's a problem of which flower they choose. They all seem to have taken a liking to a particular flower (or flowers, because those are different apiaries and flowers) in that corner. They all try to pollinate that one flower per apiary, bump in each other, and because of that they cannot finish doing its thing with the flower in a timely manner. 

Though I acknowledge that I may be totally wrong, and misinterpret what I see.

**Comment by Epic428** [comment]
So all bees scan for flowers in the same order. As such, if multiple bees need the same “flower” then they’ll obviously pick the same one Bc of how they are scanning block positions. I can change this to select a random position but at the expense of performance. We’re already about as optimized as we can get without completely rewriting vanilla pathfinding so I’d like to avoid adding that expense until I am able to see what performance gains I can get with rewriting the pathfinding. You can use the honey dipper item to designate specific flower positions to bees. 

Also if your apiaries are too close together and there’s a flower in a different one that the bee wants then they’ll try to go for that one whether they can get to it or not.

as for the bees bumping each other and fighting over the flower block. See #199

**Comment by sztosz** [comment]
Players like me, those who don't read mod in game manuals, should be punished. Honey Dipper works great. I'm sorry for not reading manual.

**Comment by sztosz** [comment]
I've got another question, maybe a bug report not sure. I linked all bees to different flowers in apiary with the Honey Dipper, and they seemed to be working correctly gathering stuff from different flowers. Next day, after game running on its own for a whole day after a modpack update, when I finally got back to it, it seems that all the bees are trying to do its thing with the same one flower in a corner. Does game restart, modpack update, or time passing by reset the bee to flower linking?

**Comment by ThatGravyBoat** [comment]
yeah we kept a feature from vanilla where it had a 10% chance to remove the bees saved flower but we have removed that in the next update

**Comment by Nick633** [comment]
thank you all guys, and yes I tried the Honey Dipper and it happen the same, after my chunks where unloaded, and loaded back again the same happened.

**Comment by albertlky** [comment]
I am having the exact same problem but with tier 4 beehives. Even in one block space (with all sides covered with solid blocks), the mod bees are path finding towards flowers they cannot reach instead of the flower in the 1 block space. And those bees are not producing any honeycombs. I believe it is a bug because with the exact same setup, vanilla bees do not have the same problem. I am playing the sky bees modpack.

**Comment by Epic428** [comment]
That’s because in our code and vanillas code when selecting a flower the ability to get to that location is not taken into account. It would be even more overhead on top and already extremely inefficient system and until I can optimize pathfinding in general I’m reluctant to add anything else that compromises performance even if it is beneficial.

**Comment by albertlky** [comment]
I would like to ask the detection area of a bee (to select a flower) is based on the bee hive location or the bees themself?

**Comment by ThatGravyBoat** [comment]
its based on the bee and its area is an 11 block by 11 block cube centered on the bee

**Comment by albertlky** [comment]
So if I want a efficient setup, I need to keep the bees in a 1 block space, and keep another 1 block setup 11 blocks apart(for the same type of pollination block i.e. bee flowers)? Thanks for the quick response btw!!

**Comment by Epic428** [comment]
Or uses the honey dipper on the bee so it has a designated flower Bc in our latest alpha they don’t forget flowers. So once set they should be good until the flower ceases to exist.

**Comment by albertlky** [comment]
Actually I have tried using honey dipper in a 5x5 setup and assign the bees to different flowers. However they went back to the same flower after entering and exiting the hives. The version of modpack is the curseforge version 3 fixed. Is that the alpha version you mentioned?

**Comment by ThatGravyBoat** [comment]
version 0.6.6a is the alpha version

**Comment by albertlky** [comment]
Ohhh seems like curseforge is using 0.6.5b maybe i should manually upgrade the jar file

**Comment by albertlky** [comment]
This is weird. After updating, the bees in 1 block setup do not path-find to flowers they cant reach. Yet, even with the help of a honey dipper in a 5x5 setup, the bees still gathering at that one specific flower after entering and exiting the hive. Now the 1 blocks setup works fine for me, but I would like to mention the dipper issue here just in case. If there are any other issues encountered, i will also report here. Thanks for all the great work!!

**Comment by Epic428** [comment]
Shouldn’t be an issue with the dipper. All it does is set the flowerPos of the bee to the blockPos of the flower you clicked on as long as the flower is a valid flower for that bee. So once you’ve set it, unless something makes the flowerPos null or the flower doesn’t exist any more it should always continue going to that same location

**Comment by sztosz** [comment]
> Or uses the honey dipper on the bee so it has a designated flower Bc in our latest alpha they don’t forget flowers. So once set they should be good until the flower ceases to exist.

I'm using 1.16.5-0.6.6a and those damn bees seem to forget the flowers anyway.

**Comment by Epic428** [comment]
Yeah it’s because if their pollination attempts fail the flower position gets reset. I have some code in dev for what was supposed to be an experimental performance mode that would eliminate that issue. However, it doesn’t really have a significant impact on performance and as such it will be getting a name change to not be misleading.

**Comment by Epic428** [comment]
Changes are made in dev to address this
