### ISSUE TITLE
A Beeguide

### ISSUE THREAD

**Issue by IvorAmlug** [Team-Resourceful/ResourcefulBees#23]
Is still not understand how every feature works (how to breed bees for ex)
So a guide maybe in form of a book that explains some features of the mod would be realy helpfull.
There is not much to say about this. I thought it would be really helpfull for people that are new to the mod like me to learn it.

**Comment by DrDarkfire** [comment]
There will not be plans to make a book guide. Everything you need to know for using this mod in a modpack is on our wiki. We even have a web tool to make bees so you don't have to mess with the jsons. Bee breeding shows up in JEI. You just need to click the test at the top if JEI. It shows all the mod's JEI catagories. We are working on the breeding showing up on uses/recipes for spawn eggs.

Because this is a pack dev oriented mod, we are taking a hands off approach to usage of the mod. It is up to the pack dev to clarify the usage of bees if they want.
![beejei](https://user-images.githubusercontent.com/20916594/88074959-22c97a00-cb46-11ea-95fb-41b51009168c.png)
