### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by JKcaramel** [Team-Resourceful/ResourcefulBees#242]
Most of my friends could play the same mods and connect sever normally, but one of my friend keeps crashing upon startup, crash report showing failure upon load of resourceful bee
Below is the crash report
[message (1).txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6487652/message.1.txt)

**Comment by Epic428** [comment]
Evidently they’ve either got a corrupted installation, or they’ve modified one of the bees. Because the error message states that one of the bees failed validation.

also I would recommend updating to the latest version of our mod. 99.99% of 1.16.4 mods will work on 1.16.5 so there’s no reason not to update and you’ll get a ton of fixes and performance improvements
