### ISSUE TITLE
Slimy, Blaze, and Glowing Bees do not have Flowers/Blocks to produce Honeycombs

### ISSUE THREAD

**Issue by Tizby101** [Team-Resourceful/ResourcefulBees#40]
Slime Bees, Blaze Bees, and Glowstone Bees do not produce honeycomb when given blocks and flowers.  

Slimy Bees were given various flowers (Minecraft and other Mods), a Slime Block, and a Lily Pad with no effects toward producing any Slimy Honeycombs.  Blaze Bees were given various flowers (Minecraft and other Mods), a Blaze Mesh (from Botania), Nether Quarts Block, Glowstone, Nether Wart, Netherrack, and Nether Brick with no effects toward producing any Blaze Honeycombs.  Glowstone Bees were given various flowers (Minecraft and other Mods), Glowstone, Glowstone Lamp, Nether Wart, Netherrack, and Nether Brick with no effects toward producing any Glowing Honeycombs.  

The bees never were attached to anything unlike other bees where they dance around the blocks/flowers.  The bees never increased the level of the hive based on comparator signal.  The Bees were by themselves with no other Bee interaction.  

In JEI, no images show up for either Slimy, Blaze, or Glowing Bees under the Bee Flower tab.  (image attached)
![glowing](https://user-images.githubusercontent.com/71547453/93783515-c17f5f00-fbf9-11ea-80d2-0273fba7f96c.JPG) 

It makes sense to have the Slimy Bee be a slime block, the Blaze Bee to be nether wart, and the Glowing Bee to be glowstone.  

**please complete the following information:**
 - Forge Version 31.2.36
 - All the Mods - Mod Version 2.21
 - Resourceful Bees Version - 1.15.2-0.3.8a

**Comment by ThatGravyBoat** [comment]
Please provide your latest.log

**Comment by Tizby101** [comment]
[2020-09-21-3.log.gz](https://github.com/Resourceful-Bees/ResourcefulBees/files/5258028/2020-09-21-3.log.gz)
[2020-09-21-2.log.gz](https://github.com/Resourceful-Bees/ResourcefulBees/files/5258029/2020-09-21-2.log.gz)
[2020-09-21-1.log.gz](https://github.com/Resourceful-Bees/ResourcefulBees/files/5258030/2020-09-21-1.log.gz)

**Comment by ThatGravyBoat** [comment]
Hmm if was anything on our end there would be errors so its an issue with the block or tag provided in the bees json.
Looking at the tag for those bees its likely due to there being the blocks which is provided not being in 1.15
So im gonna close this because not much we can do when its most likely an issue with the bees json itself because the system is fine because other bees work so its either the tag provide with that bee so I would suggest reporting it to the pack devs. If you find out its not because of the tag having the wrong block ids in there then make a new issue :)

**Comment by Tizby101** [comment]
No this is not an issue with the pack, this is an issue with the tags within minecraft.  you dont have the correct tags in the bees json.  they should be the suggestions I mentioned before.  You are assuming this will be added to other packs with those tags.  The tags should reference native minecraft items with native minecraft tags.  If resourceful bees is added to just minecraft, then the game should work.  You need to fix the tags within your version for 1.15.2, not 1.16 versions!

**Comment by WhitePhant0m** [comment]
Those bees are provided by the pack makers, aka. me(ATM5/6), and those bees were originally ported from 1.16.1 and I forgot to change their flower types to be correct for 1.15.2 since it doesn't have the same stuff, and also, they use tags that I made. This is not an issue on their end, it's an issue on our end. ~~I will be fixing those when I have the time, but I'm mostly working on ATM6 1.0+ now.~~ From the looks of it, I did fix this issues a week ago(?) but my newer datapack which has the tag fixes isn't in the latest release... I'll try and get them in the next release.
