### ISSUE TITLE
Honey Generator energy jumping between positive, negative, and maximum

### ISSUE THREAD

**Issue by ViRb3** [Team-Resourceful/ResourcefulBees#72]
**To Reproduce**
1. Place Honey Generator
2. Put 16 Honey Bottles inside
3. Observe the energy bar randomly jump between 10kRF to -10kRF to 5kRF to -33kRF to 100kRF (max). Values are just examples.

**Expected behavior**
Well, normal energy generation.

**Screenshots**
![image](https://user-images.githubusercontent.com/2650170/99148165-ed194580-268e-11eb-9cca-431ad2d88ff7.png)

**please complete the following information:**
 - Forge Version: forge-35.0.14
 - Mod Version: resourcefulbees-1.16.3-0.5.5b
- Modpack: All the Mods 6 - 1.3.0

**Comment by ViRb3** [comment]
Now it seems like it's stuck to toggling between -31kRF and 100kRF permanently. Video below:
[2020-11-14_15-37-28.zip](https://github.com/Resourceful-Bees/ResourcefulBees/files/5540780/2020-11-14_15-37-28.zip)

**Comment by Epic428** [comment]
Is this observed when playing on a server?

I haven’t had this occur in dev tests at all. I would also be willing to be that it’s more so a visual glitch and that the actually contained power isn’t changing. I’ll look into what’s causing it though and fix it.

**Comment by ViRb3** [comment]
It is on a sever, yes. Thanks for the time!

**Comment by Epic428** [comment]
Hey sorry for the late reply. I know exactly what the issue is and it’s a super simple fix on my side. When I redid the generator outputs and capacities I completely overlooked it. Will show in the next update when I get it finished.

As a reference: dedicated servers convert integers to shorts so I have to bit shift the value and split it to two 16bit integers instead.

**Comment by Vaerys-Dawn** [comment]
fixed
